#!/bin/bash

docker build -t nlp-jsonlines .
docker tag nlp-jsonlines:latest $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/sagemaker-studio-d-ebafjgrwlbqa:v1
docker push $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/sagemaker-studio-d-ebafjgrwlbqa:v1