#!/bin/bash

VERSION="application-jsonlines-single-items"

docker build -t nlp-jsonlines .
docker tag nlp-jsonlines:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/sagemaker-studio-d-ebafjgrwlbqa:$VERSION
docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/sagemaker-studio-d-ebafjgrwlbqa:$VERSION